#!/usr/bin/env bash
# Markdown / text report helpers

REPORT_LINES=()
REPORT_MODE="dry-run"
REPORT_PROFILE="smb-default"
REPORT_HOST="$(hostname -f 2>/dev/null || hostname || echo unknown)"
REPORT_PLANNED=0
REPORT_OK=0
REPORT_APPLIED=0
REPORT_SKIPPED=0

report_reset() {
  REPORT_LINES=()
  REPORT_PLANNED=0
  REPORT_OK=0
  REPORT_APPLIED=0
  REPORT_SKIPPED=0
}

report_add() {
  REPORT_LINES+=("$1")
}

report_section() {
  report_add ""
  report_add "## $1"
  report_add ""
}

report_item() {
  local status="$1" msg="$2"
  case "$status" in
    planned)  REPORT_PLANNED=$((REPORT_PLANNED + 1)); report_add "- [ ] **PLANNED** — $msg" ;;
    ok)       REPORT_OK=$((REPORT_OK + 1)); report_add "- [x] **OK** — $msg" ;;
    applied)  REPORT_APPLIED=$((REPORT_APPLIED + 1)); report_add "- [x] **APPLIED** — $msg" ;;
    skipped)  REPORT_SKIPPED=$((REPORT_SKIPPED + 1)); report_add "- [ ] **SKIPPED** — $msg" ;;
    *)        report_add "- $msg" ;;
  esac
}

report_render_md() {
  local mode_label
  if [[ "$REPORT_MODE" == "apply" ]]; then
    mode_label="APPLY (changes may have been written)"
  else
    mode_label="DRY-RUN (no system changes)"
  fi

  echo "# AutoHarden Report"
  echo
  echo "| Field | Value |"
  echo "|-------|-------|"
  echo "| Brand | **${AH_BRAND}** · [run-as-daemon.ru](${AH_SITE}) |"
  echo "| Toolkit | AutoHarden-Toolkit v${AH_VERSION} |"
  echo "| Host | \`${REPORT_HOST}\` |"
  echo "| Profile | \`${REPORT_PROFILE}\` |"
  echo "| Mode | ${mode_label} |"
  echo "| Generated | $(ah_timestamp) |"
  echo
  echo "> Use this report with the [Director Checklist](docs/director-checklist.md)."
  echo "> Default CLI mode is **dry-run**; real changes require explicit \`--apply\`."
  echo
  echo "## Summary"
  echo
  echo "| Metric | Count |"
  echo "|--------|------:|"
  echo "| Already OK | ${REPORT_OK:-0} |"
  echo "| Planned / would change | ${REPORT_PLANNED:-0} |"
  echo "| Applied | ${REPORT_APPLIED:-0} |"
  echo "| Skipped | ${REPORT_SKIPPED:-0} |"
  echo

  local line
  for line in "${REPORT_LINES[@]:-}"; do
    printf '%s\n' "$line"
  done

  echo
  echo "---"
  echo
  echo "*Generated by AutoHarden-Toolkit · ${AH_BRAND} · MIT OSS with [paid support](${AH_SITE}) available.*"
}

report_write() {
  local out="$1"
  local content
  content="$(report_render_md)"
  if [[ -n "$out" && "$out" != "-" ]]; then
    mkdir -p "$(dirname "$out")"
    printf '%s\n' "$content" > "$out"
    ah_log "Report written to $out"
  fi
  printf '%s\n' "$content"
}
